### ISSUE TITLE
[Request] Remove command block access

### ISSUE THREAD

**Issue by OscarHullFirebase** [kaboomserver/server#112]
Hi. I have logged on to Kaboom and have been immediately killed using command blocks. If you could disable command blocks, that would be great.
Thank You,
Hullraiser, a player of your server

**Comment by OscarHullFirebase** [comment]
has anyone checked this out yet?

**Comment by infamousgriefer** [comment]
its clearly anarchy, freeop and creative, they can do anything they want. so cope with it

**Comment by NexusSfan** [comment]
That's not how the server works.
