### ISSUE TITLE
[Request] Kaboom.pw old files from 2018 extremely rare

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#122]
https://archive.org/details/worlds_202403

**Comment by glassesglasses8** [comment]
I found Kaboom.pw old files off of an old hardrive from 2016

**Comment by IuCC123** [comment]
NO WAY!

**Comment by B2RT0SZM77** [comment]
THAT'S CRAZY

**Comment by oie1** [comment]
NOW THIS IS CRAZY!1!!
![image](https://github.com/kaboomserver/server/assets/58725944/502a0e89-fa28-4a6f-97a9-e018a07640b3)
