### ISSUE TITLE
/forceload should be removed

### ISSUE THREAD

**Issue by LunaWasFlaggedAgain** [kaboomserver/server#27]
bots can spam /forceload to load alot of chunks, causing the server to crash

here's a example on my kaboom clone:
![image](https://user-images.githubusercontent.com/90072930/132099763-3c2a8e51-d58a-41ea-8eff-5f5d77bc51b0.png)

yes, that's right. a single /forceload causes the server to freeze for 11 seconds to load chunks.

/forceload serves no use other than loading chunks - so I feel like it should be removed (instead of just patched to not do this)

**Comment by business-goose** [comment]
no

**Comment by LunaWasFlaggedAgain** [comment]
> no

Why not?

**Comment by IuCC123** [comment]
I noticed that /forceload seems to lag the server as well. I saw a bot spamming /forceload and it managed to freeze the server for about 10 seconds (it also dropped the TPS by a lot). It would be nice if it got blocked, its not that helpful anyways.

**Comment by business-goose** [comment]
necessary to run forceload before /setblocking an unloaded chunk. e.g. creating a command block core in a chunk before you tp to it. maybe instead of removing the feature entirely, consider ratelimiting it

**Comment by LunaWasFlaggedAgain** [comment]
> would like to see teleport command being unblocked and instead ratelimited

we don't need to ratelimit it, just block `@e` and `@a`, and don't allow it in /execute

**Comment by business-goose** [comment]
> > would like to see teleport command being unblocked and instead ratelimited
> 
> we don't need to ratelimit it, just block `@e` and `@a`, and don't allow it in /execute

i'd disagree, bots that just spammed /tp <random coord> <random coord> <random coord> a bunch were pretty much as effective but blocking @e and @a and not allowing it in /execute would be a good first step

**Comment by allinkdev** [comment]
@LunaWasFlaggedAgain Does this issue still exist on 1.18.2 & Scissors? If so, we might be able to contribute a patch that optimizes /forceload and maybe even /fill. Seems like a much better option than just outright blocking the command.

**Comment by LunaWasFlaggedAgain** [comment]
> @LunaWasFlaggedAgain Does this issue still exist on 1.18.2 & Scissors? If so, we might be able to contribute a patch that optimizes /forceload and maybe even /fill. Seems like a much better option than just outright blocking the command.

I just checked, and it seems like it still exists on Scissors 1.19.3, although the freeze time is much lower than 11 seconds (atleast on my computer). Closing this issue as I no longer believe that removing the command is a good idea.
