### ISSUE TITLE
Very bad guy deopping me

### ISSUE THREAD

**Issue by win20-official** [kaboomserver/server#56]
This guy is deopping me and also toxic: JorgenBoost00

**Comment by sdfsdfdsffsd** [comment]
Shut the fuck up niga

**Comment by win20-official** [comment]
You are deopping me + i have Lunar Client

**Comment by sdfsdfdsffsd** [comment]
+ you don't have brain

**Comment by win20-official** [comment]
![image](https://user-images.githubusercontent.com/80408876/177001699-23f122f9-37ae-4316-a8fb-63421afee125.png)

**Comment by win20-official** [comment]
do you have brain now

**Comment by sdfsdfdsffsd** [comment]
you don't have brain

**Comment by win20-official** [comment]
see the picture

**Comment by sdfsdfdsffsd** [comment]
no

**Comment by win20-official** [comment]
yes

**Comment by sdfsdfdsffsd** [comment]
no

**Comment by win20-official** [comment]
yes

**Comment by sdfsdfdsffsd** [comment]
no
![500_F_51140582_3DqQkxiERjRvCHhBLwr7qGsN9bQZb7IV](https://user-images.githubusercontent.com/108529539/177001815-0d2f147b-1b10-4b97-88ef-0cf6b4d5b68d.jpg)

**Comment by win20-official** [comment]
![pobrane](https://user-images.githubusercontent.com/80408876/177001922-a86326ce-79ce-4e56-8e50-44d1ea8b9941.png)

**Comment by win20-official** [comment]
in your brain is tnt

**Comment by win20-official** [comment]
yes

**Comment by sdfsdfdsffsd** [comment]
![wannacry](https://user-images.githubusercontent.com/108529539/177002055-7f810438-74fb-4e9a-88cf-1b699f8fd3cf.jpg)
this is your brain

**Comment by win20-official** [comment]
![pobrane (1)](https://user-images.githubusercontent.com/80408876/177002079-b4394f9a-6c84-4332-8e20-70ab5854e383.png)
this is my brain

**Comment by sdfsdfdsffsd** [comment]
![wannacry](https://user-images.githubusercontent.com/108529539/177002084-a0d8f111-4028-4498-bb61-8aef50888050.jpg)
no, this is your brain

**Comment by win20-official** [comment]
![pobrane](https://user-images.githubusercontent.com/80408876/177002092-2aba5cbe-21e7-4d0e-b49b-a42fcb132f79.png)
this is your brain

**Comment by sdfsdfdsffsd** [comment]
![wannacry](https://user-images.githubusercontent.com/108529539/177002109-38cbe762-ba23-4fa9-8608-2e881ea680fb.jpg)
this is your fucking brain

**Comment by win20-official** [comment]
go to a doctor

**Comment by sdfsdfdsffsd** [comment]
shut the fuck up

**Comment by win20-official** [comment]
![pobrane (1)](https://user-images.githubusercontent.com/80408876/177002131-0b3b4b95-c084-44a9-8df0-df320dbb6dd2.png)
@win20-official's brain (real)

**Comment by win20-official** [comment]
you use bing as search engine

**Comment by sdfsdfdsffsd** [comment]
no, i use google search engine

**Comment by win20-official** [comment]
my search engine:
![image](https://user-images.githubusercontent.com/80408876/177002256-af2b39cc-e8aa-4428-b893-feea82ce15bc.png)

your search engine:
![image](https://user-images.githubusercontent.com/80408876/177002289-28c7c581-f2e8-4fe0-b1a0-21fc4d8b596b.png)

**Comment by win20-official** [comment]
yes

**Comment by sdfsdfdsffsd** [comment]
my search engine:
![nnn](https://user-images.githubusercontent.com/108529539/177002342-5e78a5c7-8ba3-42ab-961f-220d5f9ce938.PNG)
