### ISSUE TITLE
when I disable fast mode worldedit //undo is not working

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#60]
when I disable fast mode worldedit //undo is not working
![image](https://user-images.githubusercontent.com/109359960/180854580-b666af96-f59a-4ec6-8ef6-39f8265f5c18.png)

**Comment by allinkdev** [comment]
This is because you have Fast mode enabled. Fast mode does not save any history. To use //undo, you must disable fast mode.
