### ISSUE TITLE
fix /locate

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#63]
![image](https://user-images.githubusercontent.com/109359960/182330072-866a7782-9b74-43dd-8ee8-75a3b679c542.png)
please fix /locate

**Comment by allinkdev** [comment]
The translation key necessary for the command feedback is not present on your 1.12.2 client. This isn't a bug, upgrade your client.

**Comment by keeddasr** [comment]
Sir. Wurst client is a hack, hacks are not supported by the Kaboom Server as they are 3rd party clients.
