### ISSUE TITLE
world 3 is blank

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#66]
![2022-08-04_13 41 56](https://user-images.githubusercontent.com/109359960/182851138-b4d7dbe7-3843-43f1-9f25-c6fa43725c97.png)

/world 3 is blank

**Comment by glassesglasses8** [comment]
> ![2022-08-04_13 41 56](https://user-images.githubusercontent.com/109359960/182851138-b4d7dbe7-3843-43f1-9f25-c6fa43725c97.png)
> 
> /world 3 is blank

this is on the kaboom server in flatlands when I type /world 3

**Comment by allinkdev** [comment]
This might be due to lag in your connection or on the server. Closing this issue as I'm unable to reproduce.

**Comment by ChipmunkMC** [comment]
This seems to be caused by ViaVersion truncating everything outside of the old world size for older clients. Update your client to 1.17+.
