### ISSUE TITLE
I cant log in with cracked user name please fix this issue

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#73]
![image](https://user-images.githubusercontent.com/109359960/188327360-cb0ec8c2-a28d-4aaa-9b50-d98750cb011a.png)

**Comment by B2RT0SZM77** [comment]
Invalid characters in unsernaem,,...

**Comment by allinkdev** [comment]
You must join with a username that does not contain any unicode characters. The allowed charset is as follows:
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_
