### ISSUE TITLE
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#91]
![image](https://user-images.githubusercontent.com/109359960/203064549-b71ccfa0-4c1c-4ee3-8a9b-f8f0645c5da0.png)
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

**Comment by allinkdev** [comment]
This is an issue with your connection.
